package selenium_interview_questions;

import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.codehaus.plexus.util.FileUtils;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.Point;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

public class Alert_frames_windowhandles {
	
	
	
	/*

*  There are two types of alerts that we would be focusing on majorly:

     
    1. Web-based alert pop-ups
    2. Windows-based alert pop-ups
*
* Web-based popup alerts examples:- 
*   1. Windows authentication popup
    2. Windows security popup
     
*    As we know that handling windows based pop-ups is beyond WebDriver’s capabilities, thus we would exercise some
*    third-party utilities to handle window pop-ups.
*     
* Windows-based alert pop-ups:-
*     
*    What is Alert box/ Pop up box/ confirmation Box/ Prompt/ Authentication Box?
*    
*    What is Alert?
     Alert is a small message box which displays on-screen notification to give the user some kind of information or ask for 
     permission to perform certain kind of operation. It may be also used for warning purpose.
     
     1) Simple Alert

      This simple alert displays some information or warning on the screen.
      
      2) Prompt Alert.

      This Prompt Alert asks some input from the user and selenium webdriver can enter the text using sendkeys(" input…. ").
      
      3) Confirmation Alert.

       This confirmation alert asks permission to do some type of operation.
*    
*     1. Handling web-based pop-up box

     WebDriver offers the users with a very efficient way to handle these pop ups using Alert interface.

     There are the four methods that we would be using along with the Alert interface.    

 
      1) void dismiss() – The dismiss() method clicks on the “Cancel” button as soon as the pop up window appears.
      2) void accept() – The accept() method clicks on the “Ok” button as soon as the pop up window appears.
      3) String getText() – The getText() method returns the text displayed on the alert box.
      4) void sendKeys(String stringToSend) – The sendKeys() method enters the specified string pattern into the alert box.


     2. Window Based Pop-Ups     
     At times while automating, we get some scenarios, where we need to handle pop ups generated by windows like a print 
     pop up or a browsing window while uploading a file.
     
     There are several third-party tools available for handling window based pop-ups along with the selenium.
     So now let’s handle a window based pop up using Robot class.
     
     Robot class is a java based utility which emulates the keyboard and mouse actions
     
     files to be uploaded with the window based pop up.
     
     Handling window based pop-ups have always been a little tricky as we know Selenium is an automation testing tool which 
     supports only web application testing, that means, it doesn’t support windows based applications and window alert is one 
     of them.
     Robot class is a java based utility which emulates the keyboard and mouse actions and can be effectively used to handling 
     window based pop up with the help of keyboard events.
     The keyPress and keyRelease methods simulate the user pressing and releasing a certain key on the keyboard respectively.

*
*/
	
	

	public WebDriver driver=null;
	
	@Test
	public void By_passing_user_credentials_in_URL()
	{
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/lib/chromedriver2.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(2000, TimeUnit.SECONDS);
		//driver.get("https://www.flipkart.com/");
		/*
		 * e.g., http://Username:Password@SiteURL
		 * 
		 * http://rajkumar:myPassword@www.softwaretestingmaterial.com
		 * 
		 * here, Username is rajkumar and Password is myPassword SiteURL is
		 * www.softwaretestingmaterial.com
		 */
		String URL = "http://" + "rajkumar" + ":" + "myPassword" + "@" + "www.softwaretestingmaterial.com";
		driver.get(URL);
		driver.switchTo().alert().accept();
	}
	
	//@Test
	public void By_using_Alerts_in_Selenium()
	{

		driver.switchTo().alert();
		// Selenium-WebDriver Java Code for entering Username & Password as below:
		driver.findElement(By.id("userID")).sendKeys("userName");
		driver.findElement(By.id("password")).sendKeys("myPassword");
		driver.switchTo().alert().accept();
		driver.switchTo().defaultContent();

	}


	@Test
	public void Alertdemo() throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"/lib/chromedriver1.exe");
		driver = new ChromeDriver();

		// Alert Message handling

		driver.get("http://demo.guru99.com/test/delete_customer.php");

		driver.findElement(By.name("cusid")).sendKeys("53920");
		driver.findElement(By.name("submit")).submit();

		// Switching to Alert
		Alert alert = driver.switchTo().alert();

		// Capturing alert message.
		String alertMessage = driver.switchTo().alert().getText();

		// Displaying alert message
		System.out.println(alertMessage);
		Thread.sleep(5000);

		// Accepting alert
		alert.accept();
	}

	public boolean isAlertpresent() {
		try {
			driver.switchTo().alert();
			return true;

		} catch (Exception e) {

		}
		return false;
	}

	public void all_selenium_interview_questions() throws IOException {
		driver = new FirefoxDriver();
		driver.switchTo().alert().accept();
		driver.switchTo().alert().dismiss();

		// how to get alert text in selenium
		Alert text = driver.switchTo().alert();
		System.out.println(text.getText());

		/*
		 * 1) void dismiss() // To click on the 'Cancel' button of the alert.
		 * 
		 * driver.switchTo().alert().dismiss();
		 * 
		 * 2) void accept() // To click on the 'OK' button of the alert.
		 * 
		 * driver.switchTo().alert().accept();
		 * 
		 * 3) String getText() // To capture the alert message.
		 * 
		 * driver.switchTo().alert().getText();
		 * 
		 * 4) void sendKeys(String stringToSend) // To send some data to alert box.
		 * 
		 * driver.switchTo().alert().sendKeys("Text");
		 */

		// how to get no. of iframes in UI
		int frames = driver.findElements(By.tagName("iframes")).size();

		// how to switch to frames
		driver.switchTo().frame(0);
		driver.switchTo().frame("frmaename");
		driver.switchTo().frame("framewebelemet");

		// how to get windowhandle
		String pwindow = driver.getWindowHandle();

		Set<String> allwindows = driver.getWindowHandles();

		Iterator<String> allwindow = allwindows.iterator();

		String parantwindow = allwindow.next();
		driver.switchTo().window(parantwindow);

		String chiledwindow = allwindow.next();
		driver.switchTo().window(chiledwindow);
		//driver.switchTo().defaultContent();

		// wait conditions
		// implicitywait aplicable for entair page
		driver.manage().timeouts().implicitlyWait(2000, TimeUnit.SECONDS);

		// explicit wait applied some conditions where your adviseted statement popup
		// will appear after 30 sencond that time it will aplicable.

		WebDriverWait wait = new WebDriverWait(driver, 30);
		//wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("")));

		// how to do mouse over in selenium
		Actions a = new Actions(driver);
		a.moveToElement(driver.findElement(By.xpath(""))).build().perform();
		
		// how to do draganddrop
		Actions a1 = new Actions(driver);
		a1.dragAndDrop(driver.findElement(By.xpath("")), driver.findElement(By.xpath(""))).build().perform();

		// how to select data in the dropdown
		WebElement element = driver.findElement(By.xpath(""));
		Select se = new Select(element);
		se.selectByIndex(8);
		se.selectByValue("value");
		se.selectByVisibleText("text");

		// how to get the data of dropdowns
		List<WebElement> op = se.getOptions();

		

		// how to get screen shot in selenium
		File scr = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(scr, new File("C:\\text\\screenshot\\login\\" + ".png"));

		// how to get the coordinate of window
		driver.manage().window().getPosition().getX();
		driver.manage().window().getPosition().getY();

		// how to get both x & Y coordinates for window
		Point popoint = driver.manage().window().getPosition();
		popoint.getX();
		popoint.getY();

		// how get forwors and back word in window
		driver.navigate().to("https://www.gmail.com");
		driver.navigate().forward();
		driver.navigate().back();
		driver.navigate().refresh();

		// how to get currenturl of the page
		String curl = driver.getCurrentUrl();
		System.out.println(curl);

		// how to get title of the page
		String title = driver.getTitle();
		System.out.println(title);

		// how we can count similar objets presents in the page
		int size = driver.findElements(By.xpath("")).size();

		// what is the syntex of follwing sybling and following
		driver.findElement(By.xpath("//*[@id='text']/following-sibling::td[2]"));

		// what is the syntex of preceding sybling and following
		driver.findElement(By.xpath("//*[@id='text']/preceding-sibling::td[2]"));

		// how to get the chiled locator of based on the x-path
		driver.findElement(By.xpath("//*[@id='text']/child::td[2]"));

		// how you will get the 5th element of the UI----similar kind of element in the
		// UI in 5th element
		String text1 = driver.findElements(By.xpath("")).get(5).getText();
		
		System.out.println(text1);

		// how to know check boxes are selected or not
		driver.findElement(By.xpath("checkbox")).isSelected();

		// how to check that is element is displayed or not in the UI

		driver.findElement(By.xpath("")).isDisplayed();

		driver.findElement(By.xpath("")).isEnabled();

		// how to execute the javascript in selenium

		JavascriptExecutor js = ((JavascriptExecutor) driver);

		// how to get no of windows are available on the UI
		js.executeScript("return window.lenght");

		// how to maximize the window
		driver.manage().window().maximize();

		// what is the different between "/" and "//"
		// is the relative path ang / is the absolute path

		// how to get the atribute value from the webelement
		System.out.println(driver.findElement(By.xpath("")).getAttribute("name")); // here we will get name of element

		// how to tap on submit button with out using click method in selenium

		driver.findElement(By.xpath("")).sendKeys(Keys.ENTER);

		// i what to wait for particular element that time we will go for explicitywait

	}

}
